name: Deploy to Server

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Pull and deploy
        run: |
          ssh -o StrictHostKeyChecking=no admin@103.23.102.190 "
            cd /home/admin/ppko_bem_fk/ && \
            git pull --rebase && \
            cd /home/admin/deployment-nondsih && \
            ansible-playbook -i fk_mediku_ppkobem/hosts fk_mediku_ppkobem/deploy.yml && \
            ssh -o StrictHostKeyChecking=no admin@10.2.16.46 'docker restart fk_medikuappunnesid_bem-backend-1'"

      - name: Apply monitoring
        run: |
          ssh -o StrictHostKeyChecking=no admin@103.23.102.190 "
            cd /home/admin/ppko_bem_fk/ && \
            ansible-playbook -i localhost, ops/uptime-kuma/deploy.yml"
